# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Guidelines
  items:
    - label: 'Identity'
      link: '/guidelines/identity'
    - label: 'Typography'
      link: '/guidelines/typography'
    - label: 'Colour'
      link: '/guidelines/colour'